[package]
name = "meridian-examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
meridian-sdk = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "magic_figures"
path = "examples/magic_figures.rs"

[[example]]
name = "physic_figures"
path = "examples/physic_figures.rs"
